#############################################################################
# Makefile for building: bin/Prototype2D
# Generated by qmake (2.01a) (Qt 4.5.2) on: Sat Sep 26 15:22:45 2009
# Project:  Prototype2D.pro
# Template: app
# Command: /opt/qtsdk-2009.03/qt/bin/qmake -spec /opt/qtsdk-2009.03/qt/mkspecs/linux-g++ -unix -o Makefile Prototype2D.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.03/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2009.03/qt/include/QtCore -I/opt/qtsdk-2009.03/qt/include/QtGui -I/opt/qtsdk-2009.03/qt/include/QtOpenGL -I/opt/qtsdk-2009.03/qt/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qtsdk-2009.03/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.03/qt/lib -L/usr/X11R6/lib -LBox2D -lBox2D -lQtOpenGL -L/opt/qtsdk-2009.03/qt/lib -L/usr/X11R6/lib -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -lQtGui -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lGLU -lGL -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.03/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		world.cpp \
		texture.cpp \
		canvas.cpp \
		actor.cpp \
		texturemanager.cpp \
		startupdlg.cpp \
		games/pyp/background.cpp \
		games/pyp/pyp.cpp \
		games/pyp/block.cpp \
		games/pyp/toolpallette.cpp \
		games/pyp/pea.cpp \
		gamemanager.cpp \
		games/pyp/tri.cpp \
		games/template/template.cpp \
		actorjoint.cpp \
		games/force/force.cpp \
		games/tail/tail.cpp \
		games/anim/anim.cpp \
		games/jelly/jelly.cpp \
		games/jelly/jellyactor.cpp \
		games/autumn/autumn.cpp moc_mainwindow.cpp \
		moc_world.cpp \
		moc_canvas.cpp \
		moc_startupdlg.cpp \
		moc_force.cpp \
		moc_tail.cpp
OBJECTS       = main.o \
		mainwindow.o \
		world.o \
		texture.o \
		canvas.o \
		actor.o \
		texturemanager.o \
		startupdlg.o \
		background.o \
		pyp.o \
		block.o \
		toolpallette.o \
		pea.o \
		gamemanager.o \
		tri.o \
		template.o \
		actorjoint.o \
		force.o \
		tail.o \
		anim.o \
		jelly.o \
		jellyactor.o \
		autumn.o \
		moc_mainwindow.o \
		moc_world.o \
		moc_canvas.o \
		moc_startupdlg.o \
		moc_force.o \
		moc_tail.o
DIST          = /opt/qtsdk-2009.03/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.03/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.03/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.03/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.03/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/unix/opengl.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/include_source_dir.prf \
		Prototype2D.pro
QMAKE_TARGET  = Prototype2D
DESTDIR       = bin/
TARGET        = bin/Prototype2D

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_startupdlg.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Prototype2D.pro  /opt/qtsdk-2009.03/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2009.03/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.03/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.03/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.03/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.03/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/unix/opengl.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.03/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2009.03/qt/lib/libQtOpenGL.prl \
		/opt/qtsdk-2009.03/qt/lib/libQtGui.prl \
		/opt/qtsdk-2009.03/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2009.03/qt/mkspecs/linux-g++ -unix -o Makefile Prototype2D.pro
/opt/qtsdk-2009.03/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.03/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.03/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.03/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.03/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/release.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/unix/opengl.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.03/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2009.03/qt/lib/libQtOpenGL.prl:
/opt/qtsdk-2009.03/qt/lib/libQtGui.prl:
/opt/qtsdk-2009.03/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2009.03/qt/mkspecs/linux-g++ -unix -o Makefile Prototype2D.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Prototype2D1.0.0 || $(MKDIR) .tmp/Prototype2D1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Prototype2D1.0.0/ && $(COPY_FILE) --parents mainwindow.h world.h texture.h canvas.h actor.h texturemanager.h utils.h env.h startupdlg.h types.h defines.h games/pyp/background.h igame.h games/pyp/pyp.h games/pyp/block.h games/pyp/toolpallette.h games/pyp/pea.h gamemanager.h games/pyp/tri.h games/template/template.h actorjoint.h games/force/force.h games/tail/tail.h games/anim/anim.h games/jelly/jelly.h games/jelly/jellyactor.h games/autumn/autumn.h .tmp/Prototype2D1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp world.cpp texture.cpp canvas.cpp actor.cpp texturemanager.cpp startupdlg.cpp games/pyp/background.cpp games/pyp/pyp.cpp games/pyp/block.cpp games/pyp/toolpallette.cpp games/pyp/pea.cpp gamemanager.cpp games/pyp/tri.cpp games/template/template.cpp actorjoint.cpp games/force/force.cpp games/tail/tail.cpp games/anim/anim.cpp games/jelly/jelly.cpp games/jelly/jellyactor.cpp games/autumn/autumn.cpp .tmp/Prototype2D1.0.0/ && $(COPY_FILE) --parents mainwindow.ui startupdlg.ui .tmp/Prototype2D1.0.0/ && (cd `dirname .tmp/Prototype2D1.0.0` && $(TAR) Prototype2D1.0.0.tar Prototype2D1.0.0 && $(COMPRESS) Prototype2D1.0.0.tar) && $(MOVE) `dirname .tmp/Prototype2D1.0.0`/Prototype2D1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Prototype2D1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_world.cpp moc_canvas.cpp moc_startupdlg.cpp moc_force.cpp moc_tail.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_world.cpp moc_canvas.cpp moc_startupdlg.cpp moc_force.cpp moc_tail.cpp
moc_mainwindow.cpp: mainwindow.h
	/opt/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_world.cpp: Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		world.h
	/opt/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) world.h -o moc_world.cpp

moc_canvas.cpp: defines.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		actorjoint.h \
		canvas.h
	/opt/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) canvas.h -o moc_canvas.cpp

moc_startupdlg.cpp: startupdlg.h
	/opt/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) startupdlg.h -o moc_startupdlg.cpp

moc_force.cpp: igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		games/force/force.h
	/opt/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) games/force/force.h -o moc_force.cpp

moc_tail.cpp: igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		games/tail/tail.h
	/opt/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) games/tail/tail.h -o moc_tail.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_startupdlg.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_startupdlg.h
ui_mainwindow.h: mainwindow.ui
	/opt/qtsdk-2009.03/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_startupdlg.h: startupdlg.ui
	/opt/qtsdk-2009.03/qt/bin/uic startupdlg.ui -o ui_startupdlg.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		startupdlg.h \
		env.h \
		types.h \
		gamemanager.h \
		defines.h \
		games/pyp/pyp.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		actorjoint.h \
		games/template/template.h \
		games/force/force.h \
		games/tail/tail.h \
		games/anim/anim.h \
		games/jelly/jelly.h \
		games/autumn/autumn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		canvas.h \
		defines.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		actorjoint.h \
		env.h \
		igame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

world.o: world.cpp world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		env.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o world.o world.cpp

texture.o: texture.cpp texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o texture.o texture.cpp

canvas.o: canvas.cpp canvas.h \
		defines.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		actorjoint.h \
		env.h \
		igame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cpp

actor.o: actor.cpp actor.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		types.h \
		defines.h \
		texture.h \
		texturemanager.h \
		env.h \
		world.h \
		actorjoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o actor.o actor.cpp

texturemanager.o: texturemanager.cpp texturemanager.h \
		texture.h \
		env.h \
		types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o texturemanager.o texturemanager.cpp

startupdlg.o: startupdlg.cpp startupdlg.h \
		ui_startupdlg.h \
		env.h \
		types.h \
		gamemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startupdlg.o startupdlg.cpp

background.o: games/pyp/background.cpp games/pyp/background.h \
		actor.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		types.h \
		defines.h \
		world.h \
		actorjoint.h \
		env.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o background.o games/pyp/background.cpp

pyp.o: games/pyp/pyp.cpp games/pyp/pyp.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		texture.h \
		texturemanager.h \
		env.h \
		games/pyp/background.h \
		games/pyp/block.h \
		games/pyp/pea.h \
		games/pyp/tri.h \
		games/pyp/toolpallette.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pyp.o games/pyp/pyp.cpp

block.o: games/pyp/block.cpp games/pyp/block.h \
		actor.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		types.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block.o games/pyp/block.cpp

toolpallette.o: games/pyp/toolpallette.cpp games/pyp/toolpallette.h \
		actor.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		types.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolpallette.o games/pyp/toolpallette.cpp

pea.o: games/pyp/pea.cpp games/pyp/pea.h \
		actor.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		types.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pea.o games/pyp/pea.cpp

gamemanager.o: gamemanager.cpp gamemanager.h \
		igame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamemanager.o gamemanager.cpp

tri.o: games/pyp/tri.cpp games/pyp/tri.h \
		actor.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		types.h \
		defines.h \
		world.h \
		actorjoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tri.o games/pyp/tri.cpp

template.o: games/template/template.cpp games/template/template.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		texture.h \
		texturemanager.h \
		env.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o template.o games/template/template.cpp

actorjoint.o: actorjoint.cpp actorjoint.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o actorjoint.o actorjoint.cpp

force.o: games/force/force.cpp games/force/force.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		texture.h \
		texturemanager.h \
		env.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o force.o games/force/force.cpp

tail.o: games/tail/tail.cpp games/tail/tail.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		texture.h \
		texturemanager.h \
		env.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tail.o games/tail/tail.cpp

anim.o: games/anim/anim.cpp games/anim/anim.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		texture.h \
		texturemanager.h \
		env.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o anim.o games/anim/anim.cpp

jelly.o: games/jelly/jelly.cpp games/jelly/jelly.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		games/jelly/jellyactor.h \
		texture.h \
		texturemanager.h \
		env.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jelly.o games/jelly/jelly.cpp

jellyactor.o: games/jelly/jellyactor.cpp games/jelly/jellyactor.h \
		actor.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		types.h \
		defines.h \
		world.h \
		actorjoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jellyactor.o games/jelly/jellyactor.cpp

autumn.o: games/autumn/autumn.cpp games/autumn/autumn.h \
		igame.h \
		world.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/jtypes.h \
		Box2D/Common/Fixed.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2Math.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2PairManager.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2NullContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		actor.h \
		types.h \
		defines.h \
		actorjoint.h \
		texture.h \
		texturemanager.h \
		env.h \
		canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autumn.o games/autumn/autumn.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_world.o: moc_world.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_world.o moc_world.cpp

moc_canvas.o: moc_canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvas.o moc_canvas.cpp

moc_startupdlg.o: moc_startupdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startupdlg.o moc_startupdlg.cpp

moc_force.o: moc_force.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_force.o moc_force.cpp

moc_tail.o: moc_tail.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tail.o moc_tail.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

